[package]
name = "flatgeobuf"
version = "0.4.1"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
description = "FlatGeobuf for Rust."
homepage = "https://flatgeobuf.org/"
repository = "https://github.com/flatgeobuf/flatgeobuf/tree/master/src/rust"
readme = "README.md"
documentation = "https://docs.rs/flatgeobuf/"
license = "ISC"
keywords = ["geo", "r-tree", "spatial"]

[dependencies]
flatbuffers = "0.6"
byteorder = "1.4.2"
geozero = "0.6.0"
async-trait = "0.1.42"
reqwest = "0.11.0"
bytes = "1.0.1"
log = "0.4.13"
fallible-streaming-iterator = "0.1.9"

[dev-dependencies]
geozero-core = "0.6.1"
rand = "0.8.2"
hex = "0.4.2"
criterion = "0.3.3"
tempfile = "3.2.0"
tokio = { version = "1.0.2", default-features = false, features = ["rt-multi-thread"] }

[[bench]]
name = "read"
harness = false
[[bench]]
name = "geojson"
harness = false

#[patch.crates-io]
# Patch geozero dependencies (dev only)
#geozero = { path = "../../../../rust/geozero/geozero" }
